.TH 3DCOIN-CLI "1" "June 2016" "3dcoin-cli 0.12"
.SH NAME
3dcoin-cli \- a remote procedure call client for 3DCoin Core. 
.SH SYNOPSIS
3dcoin-cli [options] <command> [params] \- Send command to 3DCoin Core. 
.TP
3dcoin-cli [options] help \- Asks 3DCoin Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the 3dcoin-cli program. 3dcoin-cli is an RPC client used to send commands to 3DCoin Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fB3dcoind\fP, \fB3dcoin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
