
  name: 3dcoin
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Single-line elevator pitch for your amazing snap # 79 char long summary
  description: |
    This is 3dcoin description. You have a paragraph or two to tell the
    most important story about your snap. Keep it under 100 words though,
    we live in tweetspace and your description wants to look good in the snap
    store.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  3dcoind:
    command: 3dcoind
    plugs: [network, network-bind]
    environment:
      # Override HOME so the bitcoin datadir is located at
      # ~/snap/3dcoin/common/.3dcoin instead of
      # ~/snap/3dcoin/current/.3dcoin, and each new version of the bitcoin
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  3dcoin-qt:
    command: desktop-launch 3dcoin-qt
    plugs: [network, network-bind, desktop, x11]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  3dcoin-cli:
    command: 3dcoin-cli
    plugs: [network]
    environment:
      HOME: $SNAP_USER_COMMON
      
  parts:
    3dcoin:
      # See 'snapcraft plugins'
      plugin: nil
  

